# Generated by Django 5.2.17 on 2026-09-14 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_email', models.EmailField(blank=True, help_text='Если не указана, используется почта аккаунта.', max_length=254, verbose_name='почта для уведомлений')),
                ('notify_days_before', models.PositiveSmallIntegerField(default=3, verbose_name='предупреждать за, дней')),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='месячный бюджет, ₽')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
            },
        ),
    ]
