# Generated by Django 5.2.17 on 2026-09-14 14:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='название')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='код')),
                ('color', models.CharField(help_text='HEX, например #4F46E5', max_length=7, verbose_name='цвет на диаграмме')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например, «Т-Банк»', max_length=64, verbose_name='название')),
                ('kind', models.CharField(choices=[('card', 'Банковская карта'), ('account', 'Счёт / баланс'), ('other', 'Другое')], default='card', max_length=16, verbose_name='тип')),
                ('last4', models.CharField(blank=True, max_length=4, verbose_name='последние 4 цифры')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'способ оплаты',
                'verbose_name_plural': 'способы оплаты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('website', models.URLField(blank=True, verbose_name='сайт')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='subscriptions.category', verbose_name='категория')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_services', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'сервис',
                'verbose_name_plural': 'сервисы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Необязательно, например «Семейный». По умолчанию используется название сервиса.', max_length=100, verbose_name='название тарифа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена за период, ₽')),
                ('billing_type', models.CharField(choices=[('monthly', 'Ежемесячно'), ('yearly', 'Ежегодно'), ('trial', 'Пробный период')], default='monthly', max_length=16, verbose_name='тип оплаты')),
                ('start_date', models.DateField(verbose_name='дата начала')),
                ('trial_end_date', models.DateField(blank=True, null=True, verbose_name='конец пробного периода')),
                ('billing_period_after_trial', models.CharField(blank=True, choices=[('monthly', 'Ежемесячно'), ('yearly', 'Ежегодно')], max_length=16, verbose_name='оплата после пробного периода')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.paymentmethod', verbose_name='способ оплаты')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.service', verbose_name='сервис')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'подписка',
                'verbose_name_plural': 'подписки',
                'ordering': ['-is_active', 'service__name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='сумма, ₽')),
                ('paid_at', models.DateField(verbose_name='дата списания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.paymentmethod', verbose_name='способ оплаты')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription', verbose_name='подписка')),
            ],
            options={
                'verbose_name': 'платёж',
                'verbose_name_plural': 'платежи',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('trial_ending', 'Окончание пробного периода'), ('renewal_upcoming', 'Скорое продление')], max_length=32, verbose_name='тип')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('dashboard', 'Дашборд')], max_length=16, verbose_name='канал')),
                ('event_date', models.DateField(help_text='Например, дата окончания пробного периода.', verbose_name='дата события')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='отправлено')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='subscriptions.subscription', verbose_name='подписка')),
            ],
            options={
                'verbose_name': 'уведомление',
                'verbose_name_plural': 'журнал уведомлений',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='название')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='добавлен')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription', verbose_name='подписка')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.tag', verbose_name='тег')),
            ],
            options={
                'verbose_name': 'тег подписки',
                'verbose_name_plural': 'теги подписок',
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', through='subscriptions.SubscriptionTag', to='subscriptions.tag', verbose_name='теги'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('name',), name='unique_catalog_service_name'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'name'), name='unique_custom_service_name_per_owner'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['subscription', 'paid_at'], name='subscriptio_subscri_89dc6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='notificationlog',
            constraint=models.UniqueConstraint(fields=('subscription', 'kind', 'channel', 'event_date'), name='unique_notification_per_event'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_tag_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='subscriptiontag',
            constraint=models.UniqueConstraint(fields=('subscription', 'tag'), name='unique_subscription_tag'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'is_active'], name='subscriptio_user_id_24ff08_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='subscription_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('billing_type', 'trial'), _negated=True), models.Q(('trial_end_date__isnull', False), models.Q(('billing_period_after_trial', ''), _negated=True)), _connector='OR'), name='subscription_trial_fields_required'),
        ),
    ]
